### ISSUE TITLE
About the running code problem

### ISSUE THREAD

**Issue by zwyking** [tlliao/Perception-based-seam-cutting#1]
Hi,
thanks for your excellent work. I have trouble running your MBS code with the below wrong warning.
![QQ截图20220425154353](https://user-images.githubusercontent.com/45560490/165043656-589e61f7-d839-4052-a941-c4aeb6dbd575.jpg)

Have you ever met such problem in your implementation?

Best regard.

**Comment by tlliao** [comment]
I have met this problem before, but I forget the reason why this happens. It may be due to the existence of the chinese characters in your absolute path (I'm not sure).

If the "compile_win.m" is running successfully, the demo should have no problem.

**Comment by zwyking** [comment]
Ok, thanks for your patient response. I have successfully run it~
